{{- if .Values.ingress.rest.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "matchbox.fullname" . }}-rest
  labels:
    {{- include "matchbox.labels" . | nindent 4 }}
  {{- with .Values.ingress.rest.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.rest.className }}
  ingressClassName: {{ . }}
  {{- end }}
  tls:
    - hosts:
        - {{ .Values.matchbox.rest.hostname | default (printf "%s.%s.svc.cluster.local" (include "matchbox.fullname" .) .Release.Namespace) }}
      secretName: {{ include "matchbox.fullname" . }}-rest-tls
  rules:
    - host: {{ .Values.matchbox.rest.hostname | default (printf "%s.%s.svc.cluster.local" (include "matchbox.fullname" .) .Release.Namespace) }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "matchbox.fullname" $ }}-rest
                port:
                  number: {{ $.Values.service.rest.port }}
{{- end }}
