{{- if .Values.ingress.rpc.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "matchbox.fullname" . }}-rpc
  labels:
    {{- include "matchbox.labels" . | nindent 4 }}
  annotations:
    # matchbox rpc must serve TLS itself.
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
  {{- with .Values.ingress.rpc.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.rpc.className }}
  ingressClassName: {{ . }}
  {{- end }}
  tls:
    - hosts:
        - {{ .Values.matchbox.rpc.hostname | default (printf "%s.%s.svc.cluster.local" (include "matchbox.fullname" .) .Release.Namespace) }}
      secretName: {{ include "matchbox.fullname" . }}-rpc-tls
  rules:
    - host: {{ .Values.matchbox.rpc.hostname | default (printf "%s-rpc.%s.svc.cluster.local" (include "matchbox.fullname" .) .Release.Namespace) }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "matchbox.fullname" $ }}-rpc
                port:
                  number: {{ $.Values.service.rpc.port }}
{{- end }}
