apiVersion: v1
kind: Service
metadata:
  name: {{ include "matchbox.fullname" . }}
  labels:
    {{- include "matchbox.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.rpc.type }}
  ports:
    - port: {{ .Values.service.rpc.port }}
      targetPort: rpc
      protocol: TCP
      name: rpc
  selector:
    {{- include "matchbox.selectorLabels" . | nindent 4 }}
