apiVersion: v1
kind: Service
metadata:
  name: {{ include "matchbox.fullname" . }}-rest
  labels:
    {{- include "matchbox.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.rest.type }}
  ports:
    - port: {{ .Values.service.rest.port }}
      targetPort: rest
      protocol: TCP
      name: rest
  selector:
    {{- include "matchbox.selectorLabels" . | nindent 4 }}
