apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cpupooler.fullname" . }}
  labels:
    {{- include "cpupooler.labels" . | nindent 4 }}
data:
{{- range $d := .Values.poolConfigs }}
  poolconfig-{{ $d.name }}.yaml: |
    {{- $d.config | toYaml | nindent 4 }}
{{ end }}
