apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "cpupooler.fullname" . }}
  labels:
    {{- include "cpupooler.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "cpupooler.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "cpupooler.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "cpupooler.serviceAccountName" . }}
      priorityClassName: system-node-critical
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: copy-process-starter
          securityContext:
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: false
            runAsUser: 0
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/cp", "/process-starter", "/opt/bin/process-starter"]
          volumeMounts:
            - mountPath: /opt/bin
              name: opt-bin
              readOnly: false
      containers:
        - name: cpu-device-plugin
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/cpu-device-plugin", "-logtostderr"]
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /var/lib/kubelet/device-plugins/
              name: devicesock
              readOnly: false
            - mountPath: /etc/cpu-pooler
              name: cpu-pooler-config
        - name: cpusetter
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/cpusetter", "--poolconfigs=/etc/cpu-pooler", "--cpusetroot=/rootfs/sys/fs/cgroup/cpuset/kubepods", "-logtostderr"]
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /var/lib/kubelet/device-plugins/
              name: devicesock
              readOnly: true
            - mountPath: /rootfs/sys/fs/cgroup/cpuset/kubepods/
              name: kubepods
              readOnly: true
            - mountPath: /etc/cpu-pooler
              name: cpu-pooler-config
      volumes:
        - name: devicesock
          hostPath:
            path: /var/lib/kubelet/device-plugins/
            type: Directory
        - name: kubepods
          hostPath:
            path: /sys/fs/cgroup/cpuset/kubepods/
        - name: opt-bin
          hostPath:
            path: /opt/bin
            type: DirectoryOrCreate
        - name: cpu-pooler-config
          configMap:
            name: {{ include "cpupooler.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
