apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cpupooler.fullname" . }}-webhook
  labels:
    {{- include "cpupooler.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.webhook.replicas }}
  selector:
    matchLabels:
      {{- include "cpupooler.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.webhook.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "cpupooler.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.webhook.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "cpupooler.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.webhook.podSecurityContext | nindent 8 }}
      containers:
        - name: webhook
          command: ["/cpu-device-webhook", "-logtostderr", "-tls-cert-file=/tls/tls.crt", "-tls-private-key-file=/tls/tls.key", "-process-starter-path=/process-starter", "-v=5"]
          securityContext:
            {{- toYaml .Values.webhook.securityContext | nindent 12 }}
          image: "{{ .Values.webhook.image.repository }}:{{ .Values.webhook.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.webhook.image.pullPolicy }}
          resources:
            {{- toYaml .Values.webhook.resources | nindent 12 }}
          volumeMounts:
            - name: tls-ca
              mountPath: /tls-ca
            - name: tls
              mountPath: /tls
            - name: config
              mountPath: /etc/cpu-pooler
          ports:
            - name: https
              containerPort: 8443
              protocol: TCP
      volumes:
        - name: tls-ca
          secret:
            secretName: {{ include "cpupooler.fullname" . }}-tls-ca
        - name: tls
          secret:
            secretName: {{ include "cpupooler.fullname" . }}-tls
        - name: config
          configMap:
            name: {{ include "cpupooler.fullname" . }}
#        - name: opt-bin
#          hostPath:
#            path: /opt/bin
#            type: Directory
      {{- with .Values.webhook.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.webhook.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
