{{- $ca := .ca | default (genCA (printf "*.%s.svc" .Release.Namespace) 1024) -}}
{{- $altNames := list (printf "%s.%s.svc" (include "cpupooler.fullname" .) .Release.Namespace) -}}
{{- $cert := genSignedCert (printf "%s.%s.svc" (include "cpupooler.fullname" .) .Release.Namespace) nil $altNames 1024 $ca -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cpupooler.fullname" . }}-tls-ca
  labels: {{ include "cpupooler.labels" . | nindent 4 }}
data:
  rootCA.crt: {{ $ca.Cert | b64enc }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cpupooler.fullname" . }}-tls
  labels: {{ include "cpupooler.labels" . | nindent 4 }}
  annotations:
    self-signed-cert: "true"
type: kubernetes.io/tls
data:
  tls.key: {{ $cert.Key | b64enc }}
  tls.crt: {{ $cert.Cert | b64enc }}

---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: cpu-device-pod-mutator-webhook-config
webhooks:
  - name: cpu-dev-mutator.nokia.k8s.io
    sideEffects: None
    # TODO: support v1
    admissionReviewVersions: ["v1beta1"]
    timeoutSeconds: 5
    clientConfig:
      service:
        name: {{ include "cpupooler.fullname" . }}
        namespace: {{ .Release.Namespace }}
        path: "/mutating-pods"
      caBundle: {{ $ca.Cert | b64enc }}
    rules:
      - operations: ["CREATE","UPDATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    failurePolicy: Fail
