apiVersion: v1
kind: Service
metadata:
  name: {{ include "cpupooler.fullname" . }}
  labels:
    {{- include "cpupooler.labels" . | nindent 4 }}
spec:
  type: {{ .Values.webhook.service.type }}
  ports:
    - port: {{ .Values.webhook.service.port }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "cpupooler.selectorLabels" . | nindent 4 }}
