apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}
subjects:
  - kind: ServiceAccount
    name: {{ include "clusterpedia.apiserver.fullname" . }}
    namespace: {{ .Release.Namespace }}
  - kind: ServiceAccount
    name: {{ include "clusterpedia.clustersynchroManager.fullname" . }}
    namespace: {{ .Release.Namespace }}
