apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "clusterpedia.internalstorage.fullname" . }}
  namespace: {{ .Release.Namespace }}
data:
  internalstorage-config.yaml: |-
    type: {{ include "clusterpedia.storage.type" . | quote }}
    host: {{ include "clusterpedia.storage.host" . | quote }}
    port: {{ include "clusterpedia.storage.port" . }}
    user: {{ include "clusterpedia.storage.user" . }}
    database: {{ include "clusterpedia.storage.database" . }}
    log:
      slowThreshold: {{ .Values.log.slowThreshold | quote }}
