apiVersion: v1
kind: Secret
metadata:
  name: {{ include "clusterpedia.internalstorage.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "clusterpedia.internalstorage.fullname" . }}
    internalstorage.clusterpedia.io/type: {{ include "clusterpedia.storage.type" . }}
data:
  password: {{ include "clusterpedia.storage.password" . }}
