{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "k8s-snapshots.serviceAccountName" . }}
  labels:
    {{- include "k8s-snapshots.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "k8s-snapshots.labels" . | nindent 4 }}
  name: {{ include "k8s-snapshots.serviceAccountName" . }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
  - apiGroups:
      - "k8s-snapshots.elsdoerfer.com"
    resources:
      - snapshotrules
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - namespaces
      - pods
      - persistentvolumeclaims
      - persistentvolumes
    verbs:
      - get
      - list
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "k8s-snapshots.labels" . | nindent 4 }}
  name: {{ include "k8s-snapshots.serviceAccountName" . }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "k8s-snapshots.serviceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "k8s-snapshots.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}

{{- end }}
