{{- if .Values.Kubernetes -}}
{{- if .Values.fluentbit.output.kafka -}}
apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterOutput
metadata:
  name: kafka
  labels:
    fluentbit.fluent.io/enabled: "true"
    fluentbit.fluent.io/component: logging
spec:
  matchRegex: (?:kube|service)\.(.*)
  {{- with .Values.fluentbit.output.kafka }}
  kafka:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
