# Default values for cpupooler.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: gmarkey/cpu-pooler
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: 0.4.0

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# List of CPU pooler pool configurations.
# Refer to documentation for more information:
# https://github.com/nokia/CPU-Pooler
poolConfigs:
  - name: general-purpose
    config:
      pools:
        shared-pool:
          cpus: "1-3,5-7"
          hyperThreadingPolicy: multiThreaded
        default:
          cpus: "0,4"
          hyperThreadingPolicy: multiThreaded
      nodeSelector:
        # TODO: Create PR to support multiple nodeSelectors.
        # node.kubernetes.io/node-class: general-purpose
        node.kubernetes.io/instance-type: t3a.2xlarge

resources:
  requests:
    cpu: 10m
  limits:
    cpu: 10m

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext:
  runAsUser: 0
  runAsNonRoot: false

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: false
  runAsUser: 0

nodeSelector: {}

tolerations:
  - operator: Exists

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
          - key: node.kubernetes.io/node-class
            operator: Exists


webhook:
  image:
    repository: gmarkey/cpu-pooler
    pullPolicy: IfNotPresent
    tag: 0.4.0

  imagePullSecrets: []

  replicas: 2

  podAnnotations: {}

  resources:
    requests:
      cpu: 10m
    limits:
      cpu: 20m

  service:
    type: ClusterIP
    port: 443

  podSecurityContext:
    fsGroup: 65534
    runAsUser: 65534
    runAsNonRoot: true

  securityContext:
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 65534

  affinity: {}

  tolerations: []
